import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EduCertify - Result Sheet & Certificate Generator",
  description: "Generated by Safeeya Munawwar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* Ensure the page structure handles full height correctly */}
        <div className="flex flex-col min-h-screen">
          <main className="flex-1">{children}</main> {/* Main content should grow */}
          
          
        </div>

      </body>
    </html>
  );
}